
[build]
dockerfilepath="dockerfile"
builder = "dockerfile"
buildCommand = "docker-compose up --build"


[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10