[build]
builder = "nixpacks"
buildCommand = "docker-compose up --build"
dockerfilepath="dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
